package com.mycompany.pizzaapp;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author arjun
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
//        jButton1.setBorder(new RoundedBorder(10));
        //jLabel1.setIcon(new ImageIcon("bg.png"));
        loginLabel.setIcon(new ImageIcon("IMG\\buttons\\buttonLoginMainV2.png"));
        jLabel4.setIcon(new ImageIcon("IMG\\background_login.png"));
        

//        ImageIcon background = ;
//        Image img = background.getImage();
//        Image temp = img.getScaledInstance(1920, 1080, Image.SCALE_SMOOTH);
//        background = new ImageIcon(temp);
//        JLabel back = new JLabel(background);
//        back.setLayout(null);
//        back.setBounds(0, 0, 1920, 1080);

//        LoginBackBox.setBorder(new RoundedBorder(10));

    }
    //subclass for  rounde
//    private static class RoundedBorder implements Border {
//        private int radius;
//        RoundedBorder(int radius) {
//            this.radius = radius;
//        }
//        @Override
//        public Insets getBorderInsets(Component c) {
//            return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
//        }
//        @Override
//        public boolean isBorderOpaque() {
//            return true;
//        }
//        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
//            g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
//        }
//    }
    //for rounded borders 
    //https://stackoverflow.com/questions/13866252/button-with-round-edges

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        LoginBackBox = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(430, 930));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("eg: user:admin pass:1234");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("LogIn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 190, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("User Id");
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 300, 38));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField1.setMaximumSize(new java.awt.Dimension(400, 60));
        jTextField1.setMinimumSize(new java.awt.Dimension(100, 40));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 300, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Password");
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 300, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPasswordField1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jPasswordField1.setMaximumSize(new java.awt.Dimension(400, 60));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(100, 40));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 300, -1));

        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLabelMouseExited(evt);
            }
        });
        jPanel1.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 700, 210, 80));

        LoginBackBox.setBackground(new java.awt.Color(246, 246, 218));
        LoginBackBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(246, 246, 218), 10, true));
        LoginBackBox.setBorderPainted(false);
        LoginBackBox.setEnabled(false);
        LoginBackBox.setFocusPainted(false);
        LoginBackBox.setFocusable(false);
        LoginBackBox.setRequestFocusEnabled(false);
        LoginBackBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBackBoxActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBackBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 790, 680));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Github\\PizzaApp\\IMG\\background_login.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1926, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean userCheck() {
        boolean userExist = false;
        String data = "";
        String password = String.valueOf(jPasswordField1.getPassword());
        String username = jTextField1.getText();

        try {
            File file = new File("users\\loginUsers.txt");
            System.out.println(file.exists() + " file found!!!");
            Scanner in = new Scanner(file);
            while (in.hasNext()) {
                data += in.nextLine();
//                System.out.println(data);
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        System.out.println(data);

        String[] userData = data.split(";");
        System.out.println(Arrays.toString(userData));

        for (String user : userData) {
            int index = user.indexOf(",");
            System.out.println(index);
            System.out.println(user.substring(0, index));
            if (user.substring(0, index).equalsIgnoreCase(username)) {
                System.out.println("user exist");
                System.out.println(user.substring(index + 1, user.length()));
                if (user.substring(index + 1, user.length()).equals(password)) {
//                    System.out.println("logged in");
                    userExist = true;
                } else {
                    //System.out.println(user.substring(index, user.length()));
                    System.out.println("Password incorrect");
                }
            } else {
                //System.out.println(user.substring(0, index));
                System.out.println("user incorrect");

            }
        }
        return userExist;
    }
    private void loginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseEntered
        // TODO add your handling code here:
        loginLabel.setIcon(new ImageIcon("IMG\\buttons\\buttonLoginHoverV2.png"));
        
    }//GEN-LAST:event_loginLabelMouseEntered

    private void loginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseExited
        // TODO add your handling code here:
        loginLabel.setIcon(new ImageIcon("IMG\\buttons\\buttonLoginMainV2.png"));
    }//GEN-LAST:event_loginLabelMouseExited

    private void LoginBackBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBackBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBackBoxActionPerformed

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        // TODO add your handling code here:
        if (userCheck() == true) {
            Main v1 = new Main();
            v1.setIconImage(new ImageIcon("IMG\\icon.png").getImage());
            v1.setDefaultCloseOperation(HIDE_ON_CLOSE);
            v1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            v1.DataLogin(jTextField1.getText());
            v1.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid entries", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginLabelMouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
         jTextField1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        jTextField1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jPasswordField1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
        jPasswordField1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if (userCheck() == true) {
            Main v1 = new Main();
            v1.setIconImage(new ImageIcon("IMG\\icon.png").getImage());
            v1.setDefaultCloseOperation(HIDE_ON_CLOSE);
            v1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            v1.DataLogin(jTextField1.getText());
            v1.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid entries", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if (userCheck() == true) {
            Main v1 = new Main();
            v1.setIconImage(new ImageIcon("IMG\\icon.png").getImage());
            v1.setDefaultCloseOperation(HIDE_ON_CLOSE);
            v1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            v1.DataLogin(jTextField1.getText());
            v1.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid entries", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBackBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel loginLabel;
    // End of variables declaration//GEN-END:variables
}
